database:
  path: "data/fraud_detection.duckdb"
  
data_generation:
  n_transactions: 10000
  fraud_rate: 0.02
  start_date: "2024-01-01"
  end_date: "2024-12-31"

model:
  features:
    - amount
    - merchant_category
    - hour_of_day
    - day_of_week
    - customer_age
    - transaction_frequency
    - amount_percentile
  test_size: 0.2
  random_state: 42

api:
  host: "0.0.0.0"
  port: 8000
  
dashboard:
  port: 8501
  
monitoring:
  model_drift_threshold: 0.1
  data_quality_threshold: 0.95