version: 2

models:
  - name: stg_transactions
    description: "Cleaned and standardized transaction data"
    columns:
      - name: transaction_id
        description: "Unique transaction identifier"
        tests:
          - unique
          - not_null
      
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      
      - name: merchant_id
        description: "Merchant identifier"
        tests:
          - not_null
      
      - name: amount
        description: "Transaction amount"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100000
      
      - name: transaction_timestamp
        description: "Transaction timestamp"
        tests:
          - not_null
      
      - name: merchant_category
        description: "Category of the merchant"
        tests:
          - not_null
          - accepted_values:
              values: ['grocery', 'restaurant', 'gas_station', 'retail', 'online', 'entertainment', 'travel', 'healthcare', 'utilities', 'other']

  - name: stg_customers
    description: "Cleaned customer demographic data"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      
      - name: customer_age
        description: "Customer age"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 18
              max_value: 100
      
      - name: credit_score
        description: "Customer credit score"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 300
              max_value: 850

  - name: stg_merchants
    description: "Cleaned merchant data"
    columns:
      - name: merchant_id
        description: "Unique merchant identifier"
        tests:
          - unique
          - not_null
      
      - name: merchant_risk_score
        description: "Risk score for the merchant"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1